version: '3.8'
services:
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    restart: always
    build: ./backend
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/db
    ports:
      - "8080:8080"

  frontend:
    restart: always
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data:

